default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kibur_api_development
  port: 5432
  host : localhost
  username: postgres
  password: 12345678
test:
  <<: *default
  database: kibur_api_test
  port: 5432
  host : localhost
  username: postgres
  password: 12345678

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
